# Vagrantfile
default_box = "ubuntu/focal64"

Vagrant.configure("2") do |config|
  config.vm.box = default_box

  # Nome da máquina virtual
  config.vm.hostname = "zabbix-server"

  # Configuração de rede
  config.vm.network "private_network", ip: "192.168.50.4"
 
  # Configuração de recursos
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end

  # Provisionamento
  config.vm.provision "shell", path: "provision.sh"
end