
Vagrant.configure("2") do |config|
  config.vm.define "virtualbox" do |vb|
   vb.vm.box = "ubuntu/focal64"
   vb.vm.hostname = "shell.script"
  end
  config.vm.provision "shell", path: "provision.sh"
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.synced_folder "../", "/vagrant"

end
