
Vagrant.configure("2") do |config|
  
  config.vm.box = s
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder "./ansible", "/ansible"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
    vb.name = "vagrant-ansible"
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y ansible
    ansible-playbook --connection=local /ansible/playbook.yml
    ansible-playbook --connection=local /ansible/site.yml
  SHELL
end
